In [2]:
import torch
from torch.utils.data import Dataset
import pickle

In [88]:
class MarketDataset(Dataset):

    def __init__(self, file = 'datasets/data_mean_na.pkl'):
        self.file = file
        self.data = pickle.load(open(file,'rb'))
        self.day = 0
        self.symbol = 0
        self.num_days = len(self.data)
        self.num_symbols = 308

    def set_day(self, day_num):
        self.day = day_num
    
    def set_symbol(self, symbol):
        self.symbol = symbol

    def __len__(self, ):
        return len(self.data[self.day][self.symbol])


    # TODO: Should volume be normalized?
    def __getitem__(self, idx, ):
        df = dset.data[self.day][self.symbol]
        to_normalize = ['Open', 'High', 'Low', 'Close',
            'Open_prev', 'High_prev', 'Low_prev', 'Close_prev', 'SMA_10', 'SMA_20', 'SMA_50', 'SMA_200',
            'RSI_14', 'BBL_5_2.0', 'BBM_5_2.0', 'BBU_5_2.0',]
        df[to_normalize]/=df.iloc[0]['Close'] # Note that repeated application doesnt change anything
        ifeats = ['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
            'Open_prev', 'High_prev', 'Low_prev', 'Close_prev', 'Volume_prev',
            'Dividends_prev', 'hurst', 'SMA_10', 'SMA_20', 'SMA_50', 'SMA_200',
            'VOL_SMA_20', 'RSI_14', 'BBL_5_2.0', 'BBM_5_2.0', 'BBU_5_2.0',
            'BBB_5_2.0', 'BBP_5_2.0', 'MACD_12_26_9', 'MACDh_12_26_9',
            'MACDs_12_26_9','sym']
        inp_feats = df[ifeats]
        lfeats = ['(0.02, 0.01)', '(0.01, 0.005)', '(0.01, 0.02)',
            '(0.005, 0.01)']
        labels = df[lfeats]
        padding = torch.zeros(375 - idx - 1, inp_feats.values.shape[1], dtype = lol.dtype)

        return torch.vstack((torch.from_numpy(inp_feats[:idx+1].values),padding)), torch.from_numpy(labels.values[idx]), idx+1


In [89]:
dset = MarketDataset()

In [90]:
for item in dset:
    break

In [93]:
item

(tensor([[1.0009e+00, 1.0009e+00, 9.9118e-01,  ..., 2.7245e-05, 1.5725e-02,
          0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
          0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
          0.0000e+00]], dtype=torch.float64),
 tensor([0, 0, 0, 0]),
 1)

In [ ]:
df = dset.data[0][0]
to_normalize = ['Open', 'High', 'Low', 'Close',
       'Open_prev', 'High_prev', 'Low_prev', 'Close_prev', 'SMA_10', 'SMA_20', 'SMA_50', 'SMA_200',
       'RSI_14', 'BBL_5_2.0', 'BBM_5_2.0', 'BBU_5_2.0',]
df[to_normalize]/=df.iloc[0]['Close'] # Note that repeated application doesnt change anything
ifeats = ['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Open_prev', 'High_prev', 'Low_prev', 'Close_prev', 'Volume_prev',
       'Dividends_prev', 'hurst', 'SMA_10', 'SMA_20', 'SMA_50', 'SMA_200',
       'VOL_SMA_20', 'RSI_14', 'BBL_5_2.0', 'BBM_5_2.0', 'BBU_5_2.0',
       'BBB_5_2.0', 'BBP_5_2.0', 'MACD_12_26_9', 'MACDh_12_26_9',
       'MACDs_12_26_9','sym']
inp_feats = df[ifeats]
lfeats = ['(0.02, 0.01)', '(0.01, 0.005)', '(0.01, 0.02)',
       '(0.005, 0.01)']
labels = df[lfeats]

In [40]:
labels.values.shape

(375, 4)

tensor([], size=(0, 28), dtype=torch.float64)

In [68]:
torch.vstack((lol,rem))
# rem.shape

tensor([ 9.4709e-01,  9.4709e-01,  9.4533e-01,  9.4621e-01,  1.1330e+05,
         0.0000e+00,  9.3474e-01,  1.0159e+00,  9.3034e-01,  1.0044e+00,
         2.4040e+07,  0.0000e+00,  1.0000e+00,  9.4400e-01,  9.4524e-01,
         9.4702e-01,  9.5593e-01,  1.1470e+05,  9.1143e-01,  9.4406e-01,
         9.4586e-01,  9.4765e-01,  3.8032e-01,  5.9806e-01, -3.1212e-02,
         2.5263e-02, -5.6476e-02,  0.0000e+00], dtype=torch.float64)

In [65]:
lol = torch.from_numpy(inp_feats.values)

Open      High       Low  ...  MACDh_12_26_9  MACDs_12_26_9  sym
0    1.000882  1.000882  0.991182  ...       0.000027       0.015725    0
1    1.001764  1.001764  0.998236  ...       0.000027       0.015725    0
2    0.998236  0.998236  0.996473  ...       0.000027       0.015725    0
3    0.996473  0.999118  0.994709  ...       0.000027       0.015725    0
4    0.992063  0.994709  0.992063  ...       0.000027       0.015725    0
..        ...       ...       ...  ...            ...            ...  ...
370  0.944444  0.944444  0.942681  ...      -0.008142      -0.072546    0
371  0.944444  0.945326  0.943563  ...       0.002748      -0.071859    0
372  0.944444  0.946208  0.944444  ...       0.013277      -0.068540    0
373  0.946208  0.947090  0.945326  ...       0.022995      -0.062791    0
374  0.947090  0.947090  0.945326  ...       0.025263      -0.056476    0

[375 rows x 28 columns]

In [23]:
df

Open      High       Low  ...  (0.005, 0.01)  day  sym
0    1.000882  1.000882  0.991182  ...              0    0    0
1    1.001764  1.001764  0.998236  ...              0    0    0
2    0.998236  0.998236  0.996473  ...              0    0    0
3    0.996473  0.999118  0.994709  ...              0    0    0
4    0.992063  0.994709  0.992063  ...              0    0    0
..        ...       ...       ...  ...            ...  ...  ...
370  0.944444  0.944444  0.942681  ...              2    0    0
371  0.944444  0.945326  0.943563  ...              2    0    0
372  0.944444  0.946208  0.944444  ...              1    0    0
373  0.946208  0.947090  0.945326  ...              1    0    0
374  0.947090  0.947090  0.945326  ...              1    0    0

[375 rows x 33 columns]